### ISSUE TITLE
[urlgrab.py] don't consider filtered lines

### ISSUE THREAD

**Issue by sim642** [weechat/scripts#104]
I just had this happen to me that calling the urlgrab command opened an URL from a QUIT message which was filtered out by smart filter. I'd say opening links from non-visible lines isn't the desired behavior.

**Comment by Mikaela** [comment]
Just from curiosity, did it happen to be my quit message?

**Comment by sim642** [comment]
I think not.

**Comment by sim642** [comment]
Proposed fix: #107.
