### ISSUE TITLE
go.py: fuzzy searching

### ISSUE THREAD

**Issue by flowbish** [weechat/scripts#108]
I am requesting the addition of a fuzzy searching feature in the go.py script, such as used in CtrlP vim plugin or Sublime text editor. This text matching method involves subsequence matching rather than substring matching. 

For example, with fuzzy searching, the string "tbc" will match "**t**he-**b**est-**c**hannel". 

I have added fuzzy matching with heuristics in my fork: https://github.com/flowbish/scripts/commit/9dcb94d9418f4526d885aa40f9cb549b625ee238 but I am looking for approval from the author (@flashcode) and some discussion before submitting a pull request.

**Comment by rgrinberg** [comment]
+1 I've been looking for something like this. @flowbish are you still interested in upstreaming this? I could give this some testing if that's what is needed.

**Comment by flowbish** [comment]
Just noticed this, but whatever works, really. If there's already a pr for it then awesome.

**Comment by flashcode** [comment]
Fixed by PR #140.
