### ISSUE TITLE
Everytime I connect to weechat, coords.pl script is giving out an error.

### ISSUE THREAD

**Issue by karthick87** [weechat/scripts#127]
Everytime I connect to weechat, coords.pl script is giving out an error. Below is the error message.

04:34:13   ___       __         ______________        _____ 
04:34:13   __ |     / /___________  ____/__  /_______ __  /_
04:34:13   __ | /| / /_  _ \  _ \  /    __  __ \  __ `/  **/
04:34:13   __ |/ |/ / /  __/  __/ /_**  _  / / / /_/ // /_  
04:34:13   ____/|**/  _**/_**/__**/  /_/ /_/__,_/ __/  
04:34:13 WeeChat 1.3 [compiled on Sep  5 2015 10:18:25]
04:34:13 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
04:34:13 =!= Error with command "/alias copywin coords" (help on command: /help alias)
04:34:13 perl scripts loaded: buffers, coords, highmon, iset
04:34:13 python scripts loaded: buffer_autoclose, country, go
04:34:13 script: 299 scripts for WeeChat 1.3
04:34:13 Plugins loaded: alias, aspell, charset, exec, fifo, guile, irc, javascript, logger, lua, perl, python, relay, ruby, script, tcl, trigger, xfer

I am not sure what is the cause for this issue. Just recording the issue here based the IRC conversation.

**Comment by stfnm** [comment]
You get the error because the syntax of the ```/alias``` command has changed, it has to be ```/alias add copywin coords``` now.

https://github.com/weechat/scripts/blob/89e7281f9a66ebb54aa3453d4e5550ab37875577/perl/coords.pl#L901

**Comment by rjshaver** [comment]
It has never been fixed.  I continue to get the error.
