### ISSUE TITLE
autosort.py: "error buffer not found" and weird sorting

### ISSUE THREAD

**Issue by Mikaela** [weechat/scripts#14]
Whenever autosort.py does sorting, it gives this to core buffer:

```
17:32:09 =!= Error: buffer not found
17:32:09 =!= Error: buffer not found
17:32:09 =!= Error: buffer not found
17:32:09 =!= Error: buffer not found
17:32:09 =!= Error: buffer not found
17:32:09 =!= Error: buffer not found
17:32:09 =!= Error: buffer not found
```

and moves core buffer as the last buffer. I think that it should always be buffer number 1, but as I am getting that error, I don't know if it's supposed to be the last.

I have 7 networks like errors and my ```buffers.look.short_names``` is ```off```. I think that this might be related.

**Comment by de-vri-es** [comment]
@Mikaela: can you confirm it has been fixed and close the issue?

**Comment by Mikaela** [comment]
I have no idea how to reproduce this and I haven't encountered this lately, so I assume this is fixed.
