### ISSUE TITLE
sshnotify.py appears broken for 1.5

### ISSUE THREAD

**Issue by raku-cat** [weechat/scripts#150]
I can't seem to get sshnotify working, it does run because I can get it to error stuff about unset configs, but if I set an invalid address for example I don't get any error from that, and trying to just get it to touch a file on the remote machine on highlight produces nothing. I've tried a fresh weechat directory to no avail, the script does work as expected on 1.4. Running  WeeChat 1.5-rc1 (git: v1.5-rc1-13-g54151a3) [compiled on Apr 23 2016 01:09:37] on debian jessie. The only significant change to my system that has happened is I enabled multi-user.target in systemd to stop X from trying to start, I don't see how that would cause this to happen though.
Edit: was just able to confirm this as a 1.5 issue, installed 1.4 and launched with copied .weechat and it worked fine.

**Comment by flashcode** [comment]
I looked at the script (but not tested), and I see nothing that could be incompatible with WeeChat 1.5-dev.
There are some debug prints commented in the script, maybe you could try to enable them and check what's happening?

**Comment by raku-cat** [comment]
I gave it a shot, debug lines it printed look fine, I tried touching a file again to see if ANYTHING is working and nothing happend still.

**Comment by raku-cat** [comment]
Did a bit more testing and it seems like hook_process just isn't working, can't tell if it's my machine or config or version, so needs more testing but I think that's the problem here is that hook_process is borked in 1.5

**Comment by flashcode** [comment]
Hi,
I found why this is happening in 1.5: I added recently pointers in many API functions, especially hook functions, and I made all callbacks required. This script does not use a callback for hook_process.
So I just removed this strict checking, and callbacks are optional again.
Could you please try latest git version and tell me if it's OK?
Thanks.

**Comment by raku-cat** [comment]
That was it, thanks :)

**Comment by flashcode** [comment]
Fixed by this commit: weechat/weechat@eff655ab23d7735bbd38e994cbadcf782efa4dea
