### ISSUE TITLE
buffer_autoset.py 0.9: apply properties to already opened buffers

### ISSUE THREAD

**Issue by mumixam** [weechat/scripts#163]
A user was trying to use buffer_autoset to hide the buffer highmon from highmon.pl, but this doesnt work because the highmon buffer is opened before buffer_autoset.py is loaded. I found this as a workaround `/set weechat.startup.command_after_plugins "/perl reload highmon"`

**Comment by sim642** [comment]
As of version buffer_autoset.py 0.9 it does instantly apply options to buffers which are already open and match. I think the issue, however, is that it doesn't do the instant application procedure when the script and its configuration are loaded.

**Comment by mumixam** [comment]
Yea correct, if you reload highmon, or if you set the buffer property to hide 1 again it becomes hidden, my thoughts are the perl plugin gets loaded before the python one so highmon's buffer is opened before buffer_autoset is loaded. I tested this with latest version of buffer_autoset and 1.5 stable weechat

**Comment by flashcode** [comment]
That would be a reason to move this buffer_autoset script into core or as a C plugin. This way it can be loaded before anything else.
