### ISSUE TITLE
[multiline.pl] Swap default key behavior?

### ISSUE THREAD

**Issue by williamleuschner** [weechat/scripts#164]
I tried to contact the original author of this script to request this enhancement, but I was unable to locate an e-mail address, and the domain of the Jabber conference server listed in this and some of his other works failed to resolve.  
Would it be possible to add a configuration option to this script that swaps the default key behavior? Right now, it inserts a newline on `enter` and requires a different key (the provided example is `meta-s`) or timeout to actually send the message. This proposed enhancement would change that behavior to require a key combo (`meta-enter`, perhaps?) to insert a newline and just `enter` to send the message.  
From a pure usability standpoint, this seems to me like a logical enhancement. In my experience, I send far more single-line messages than multi-line messages, so an additional key combo to send single-line messages (or a timeout) tends to be frustrating.  
I would attempt this enhancement myself, but I don't know Perl and I'm a little too busy to figure out a new language right now :smiley:.  
Although I don't think this matters in an enhancement request, my Weechat version is `WeeChat 1.5 [compiled on May 15 2016 23:23:30]` and I am running it on OS X 10.11.5 through homebrew.

**Comment by budkin** [comment]
As a possible workaround you can change `ctrl-M` here 
https://github.com/weechat/scripts/blob/master/perl/multiline.pl#L378
to `meta-ctrl-M`. This will let you start a new line by pressing Alt-Enter, but you will not be able to edit pastes

**Comment by ailin-nemui** [comment]
In fact you can use weechat's built in /key bind to bind any key you want to /input insert \x0a, no need for an extra option

**Comment by williamleuschner** [comment]
Thanks, that's exactly what I was after. For anyone who finds this in the future:
I unbound `meta-s`
I rebound `ctrl-M` to `/input return`
I bound `meta-ctrl-M` to `/input insert \x0a`
I appreciate your help!

**Comment by tomasv** [comment]
There are some additional quirks present if you're using `go` along with this plugin.

The setup I arrived at is this:
```
/key bind meta-ctrl-M /input insert \x0a
/set perl.multiline.magic ""
/set perl.multiline.magic_enter_time "1"
```

With this `enter` will always send, pasting will work, `alt-enter` adds newline and does not send, and `go` autocompletion is not mangled with the magic indicator.

**Comment by sudoforge** [comment]
> ```
> /set perl.multiline.magic ""
> /set perl.multiline.magic_enter_time "1"
> ```

Note that the correct configuration key for the above quoted options must be prefixed with `plugins.var.`:

```
/set plugins.var.perl.multiline.magic ""
/set plugins.var.perl.multiline.magic_enter_time "1"
```

**Comment by diegoulloao** [comment]
doesn't work in macOs, because there is no `alt` key, I tried with `option` and `shift` but nothing happened.
Any solution?

**Comment by weechatter** [comment]
try ESC key

**Comment by diegoulloao** [comment]
Good it's working!! It's possible to key bind `alt+enter`?

**Comment by weechatter** [comment]
please refer documentation, also see /help key
