### ISSUE TITLE
autosort: An option to ignore freenode's stupidity with double-hash channels and treat ## channels as #

### ISSUE THREAD

**Issue by Zarthus** [weechat/scripts#214]
The title, while verbose, explains exactly what I want: Freenode channels have both `#` as `##`, I want `#a` to come before `##b`

**Comment by de-vri-es** [comment]
You can do that with replacement patterns:
```
/autosort replacements add ## #
```

Then all `##` will be replaced by `#` before sorting.

**Comment by Zarthus** [comment]
Neat, thanks.

I did see the option, but iset wasn't offering a description so it wasn't too clear what the purpose behind it was.
