### ISSUE TITLE
urlserver.py: error in function "urlserver_server_fd_cb"

### ISSUE THREAD

**Issue by wimstefan** [weechat/scripts#216]
urlserver.py throws an error at me since a month or so (sorry for being not more precise but I just noticed it recently and was only able to look up in the logfiles when this error appeared the first time).

```
python: stdout/stderr:   File "/home/swimmer/.weechat/python/autoload/urlserver.py", line 650, in urlserver_server_fd_cb
python: stdout/stderr:     urlserver['urls'][number][3])
python: stdout/stderr: TypeError: 'str' does not support the buffer interface
python: error in function "urlserver_server_fd_cb"
```

Using urlserver.py 2.1 with the latest weechat dev version.
Not sure if that's related to [#188](https://github.com/weechat/scripts/issues/188) that's why I'm opening a new issue.

**Comment by flashcode** [comment]
Are you using python 2 or 3? You can check that with `/debug libs` in WeeChat.

**Comment by wimstefan** [comment]
Libs:
   core:
     ncurses: 6.0 (patch 20150808)
     gcrypt: 1.7.6
     gnutls: 3.5.11
     curl: 7.54.0
     zlib: 1.2.11
   aspell: aspell 0.60.7-rc1
   perl: 5.24.1
   python: 3.4.6

**Comment by flashcode** [comment]
OK.

The script urlserver.py is supposed to work with python 3, but anyway python 2.7 is still the recommended version for WeeChat (many other python scripts will not work at all with python 3).

I'll try to reproduce the problem with this script and python 3.

**Comment by flashcode** [comment]
I'm not able to reproduce the problem with python 3.5.3.
Maybe you can try to reproduce using a default WeeChat and script config?

**Comment by wimstefan** [comment]
As said on irc already - I have the same problem with a default WeeChat & script config on python 3.4.6 ...

**Comment by flashcode** [comment]
Just tested with Python 3.4.4 (the version in Debian sid), the script works fine for me.

**Comment by wimstefan** [comment]
That's quite strange - not sure how I can debug that any further. But anyhow it's working with python 2.7.13 and I plan to stick with python 2.7 as long as possible anyway ;-)

Thanks for all your efforts!

**Comment by Al-Caveman** [comment]
Here is how I fixed it. Simply replace the code block at line `650` by this one:

```py
conn.sendall(
                'HTTP/1.1 302\r\n'
                'Location: {}\r\n\r\n'.format(
                    urlserver['urls'][number][3]
                ).encode()
            )
```

Basically, all I'm doing is transforming/encoding the string into bytes. I'm not a Python expert, but it seems that Python 3 likes it this way when sending data via sockets.

Note: I and the bug reporter are using Gentoo. So, in order to reproduce, maybe we need to look into which versions of Python are linked to `weechat`. I have not looked deeply, but just thought to share this, since I think it will be helpful to smarter people.

**Comment by flashcode** [comment]
The version 2.2 (commit 6a8e5a8d6ca193f5935c4d76f2a7a7d79f5ff266) should fix this problem.
