### ISSUE TITLE
pushover.py : API call failed with free-mobile

### ISSUE THREAD

**Issue by gbarre** [weechat/scripts#220]
Hi,

I have an issue with the version 2.0 of pushover.py and free-mobile.
After upgrading, I have set up my trigger (with my USER and TOKEN). I can receive the SMS but I have this message in the weechat buffer 

> :`[pushover] Error: API call failed. (Most likely the service is having trouble.)`

**Comment by stfnm** [comment]
Assuming you mean pushover.pl, can you try ```/set plugins.var.perl.pushover.user ""``` and see if that helps? This should disable the pushover.net service.

**Comment by gbarre** [comment]
Yes, pushover.pl.
Your solution works great, thank you
