### ISSUE TITLE
weetweet.py - authorization issue

### ISSUE THREAD

**Issue by Cyberek** [weechat/scripts#238]
I went to an issue (trying to authenticate weetweet.py plugin):
```
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/pi/.weechat/python/autoload/weetweet.py", line 1168, in oauth_proc_cb
python: stdout/stderr:     oauth_token, oauth_token_secret = parse_oauth_tokens(out)
python: stdout/stderr:   File "/home/pi/.weechat/python/autoload/weetweet.py", line 1128, in parse_oauth_tokens
python: stdout/stderr:     return oauth_token, oauth_token_secret
python: stdout/stderr: UnboundLocalError: local variable 'oauth_token' referenced before assignment
python: error in function "oauth_proc_cb"
```
OS: Raspian
Version: Stretch

**Comment by jpmenil** [comment]
@Cyberek, can you try with an up to date plugin?

**Comment by weechatter** [comment]
@jpmenil: you mean "script", no?   A "plugin" is something different in weechat. python for example is a plugin to run python scripts. so, should he update the python plugin or the weetweet.py script?

**Comment by jpmenil** [comment]
@weechatter, of course, i was meaning script not plugin :)
Anyway, @Cyberek, i remember having something similar years ago, so please give a try to the update, and let us know.

**Comment by Cyberek** [comment]
@jpmenil, @weechatter - I'm not using the functionality anymore and can't test it right now.

**Comment by thorstenkampe** [comment]
Same issue here. Latest versions of weetweet and twitter module.

**Comment by thorstenkampe** [comment]
Yes, sir!
