### ISSUE TITLE
[Feature request] buddylist.pl: auto complete buddies?

### ISSUE THREAD

**Issue by sim590** [weechat/scripts#258]
@weechatter Can you add auto completion for `/query <buddy>`?

From the code, I see some hint that [it's already implemented][autobuddy], but I'm no perl/weechat script expert and I'm not sure if it means what I think. If it's implemented, how do I enable it? It doesn't seem to be enabled by default when I try it.

[autobuddy]: https://github.com/weechat/scripts/blob/master/perl/buddylist.pl#L795

**Comment by weechatter** [comment]
the script offers autocompletion: /buddylist add|del [TAB]

/query is an internal command and not a /buddylist command. so /query autocomplete nicks using the nicklist and not the internal buddylist list. You can use mouse to click on your buddy to open a query or use /cursor if you don't want to use mouse

**Comment by sim590** [comment]
@weechatter I understand that `/query` uses the nicklist, but can't I configure weechat then to make it so `/query` uses nicklist+buddylist? For instance, can you make the buddylist public outside of buddylist context and so I could tell query to complete on both nicklist and buddylist? If that is feasible, that would be my feature request.

**Comment by weechatter** [comment]
you can't. the only solution would be manually adding the buddies to the nicklist. simply click on buddy in the buddylist to open query.

**Comment by weechatter** [comment]
there was no /cursor support in buddylist. i added it in v1.9. now you can do "/cursor go buddylist", move cursor to buddy and press "q" to open /query

**Comment by sim590** [comment]
@weechatter Thanks! This is a good alternative to what I wanted. You see, I don't have any mouse and only a 60% keyboard with no mouse support on it. I rarely lift my hand to go fetch my mouse with the small space I have. I do everything on keyboard easily (browsing, coding, playing music, etc.). In the end, I really appreciate this addition to the script. I'll just add an autocomplete word so that it issues `/cursor go buddylist` faster.

**Comment by sim590** [comment]
From #weechat:

```
07:16 <@nils_2> you can also add %(perl_buddylist) to weechat.completion.default_template
```
