### ISSUE TITLE
fish.py: function "register" not found (or failed) in file

### ISSUE THREAD

**Issue by ottre** [weechat/scripts#279]
After a recent system update, I got an error loading fish.py:

> 03:45:26  weechat     | python: loading script "/home/andrew/.weechat/python/autoload/fish.py"                                                             
> 03:45:26  weechat     | python: stdout/stderr (?): Python Cryptography Toolkit must be installed to use fish                                        
> 03:45:26  weechat =!= | python: function "register" not found (or failed) in file

Python Cryptography Toolkit is definitely installed.

This might be a distro-specific issue. I'm using Void Linux. If I downgrade python-crypto-2.6.1_9 to python-crypto-2.6.1_5 the error goes away and fish.py works properly.

**Comment by flashcode** [comment]
Hi,

Can you try in a python shell (outside WeeChat):

    import Crypto.Cipher.Blowfish

If this is working, then it should work in WeeChat as well.
Otherwise, there's an install problem with this package.

**Comment by ottre** [comment]
Import fails.

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.7/site-packages/Crypto/Cipher/Blowfish.py", line 56, in <module>
>     from Crypto.Cipher import _Blowfish
> ImportError: /usr/lib/python2.7/site-packages/Crypto/Cipher/_Blowfish.so: undefined symbol: rpl_malloc

I guess I should file a bug with the distro.

**Comment by flashcode** [comment]
OK, thanks.
Then I close the bug since it's not an issue with the script.
