### ISSUE TITLE
Autoconf error: "fifo: invalid text received in pipe"

### ISSUE THREAD

**Issue by thorstenkampe** [weechat/scripts#298]
The message `fifo: invalid text received in pipe` is printed eight times when loading autoconf.py. Nevertheless the script seems to load the configuration from `.weerc`.

WeeChat is running on Cygwin. All versions are the latest ones.

**Comment by weechatter** [comment]
the script pipes the eight header lines to weechat, not only the command lines. Fixed..
I also made the script python3 compatible.
Uploaded to weechat.org
