### ISSUE TITLE
[emoji2alias.py] UnicodeDecodeError

### ISSUE THREAD

**Issue by jrabensc** [weechat/scripts#303]
Received an error using the above mentioned plugin:

06:45 python: stdout/stderr (emoji2alias): Traceback (most recent call last):
06:45 python: stdout/stderr (emoji2alias):   File "/home/johannes/.weechat/python/emoji2alias.py", line 1487, in convert_emoji_to_aliases
06:45 python: stdout/stderr (emoji2alias):     string = unicode(string, "utf-8")
06:45 python: stdout/stderr (emoji2alias): UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 67: invalid start byte
06:45 =!= python: error in function "convert_emoji_to_aliases"
15:33 python: stdout/stderr (emoji2alias): Traceback (most recent call last):
15:33 python: stdout/stderr (emoji2alias):   File "/home/johannes/.weechat/python/emoji2alias.py", line 1487, in convert_emoji_to_aliases
15:33 python: stdout/stderr (emoji2alias):     string = unicode(string, "utf-8")
15:33 python: stdout/stderr (emoji2alias): UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 78: invalid continuation byte
15:33 =!= python: error in function "convert_emoji_to_aliases"

Using WeeChat 2.3 [compiled on Oct 21 2018 13:06:54].

**Comment by flashcode** [comment]
Error is fixed, and the script is now compatible with Python 3.
