### ISSUE TITLE
colorize_lines.pl: make possible to colorize differently actions

### ISSUE THREAD

**Issue by 3v1n0** [weechat/scripts#313]
Ideally I'd like to colorize actions with something like `/${nick_color}`, so basically showing the content in italic reusing the nick color, but this could be used to instead show all the actions all with the same colouring

**Comment by 3v1n0** [comment]
Well, I was proposing to expose a variable such as that to refer to the nick color, so that it would be possible to:
  1. Colorize actions lines with user color applying a format
  2. Colorize action lines with an unique color for all users

2. is a further improvement, while 1. was actually what I wanted, and it can be implemented also just adding an option with enum valus to permit this, but I thought that my proposal allowed more customization.

**Comment by 3v1n0** [comment]
> colorize_lines, colorize incomming message from a user with its nick color. so, where does the "/${nick_color}" come from?

Not sure what's unclear...

An user Foo, uses `/me status message`.

We colorize its status message, but would like to be able to apply also some formatting to it, so knowing what the nick color is would allow to do that

**Comment by 3v1n0** [comment]
> colorize_lines, colorize incomming message from a user with its nick color. so, where does the "/${nick_color}" come from?

Not sure what's unclear...

An user Foo, uses `/me status message`.

We colorize its status message, but would like to be able to apply also some formatting to it, so knowing what the nick color is would allow to do that

**Comment by weechatter** [comment]
i added a new option called "custom_action_text"
(customise the text attributes of ACTION message (note: content is evaluated, see /help eval))
eg.: ${color:*blue} will color the text of /me message "bold blue".

I guess thats what you asked for?

**Comment by oakkitten** [comment]
you could do this with a simple trigger...

**Comment by weechatter** [comment]
sure. there is also a trigger to replace the basic colorize_lines function
