### ISSUE TITLE
spell_correction.py: auto_pop_up_item not automatically popping up item

### ISSUE THREAD

**Issue by StarlitGhost** [weechat/scripts#318]
As the title says. Latest weechat 2.5-dev and script version 0.8.1

Not displaying automatically: ![no suggestions](https://i.imgur.com/XbeEcgu.png)

Does still appear after pressing tab: ![suggestions after tab](https://i.imgur.com/GpRkTrT.png)

Script settings: ![settings](https://i.imgur.com/0IDuvkx.png)

**Comment by weechatter** [comment]
Thanks for reporting, fixed in v0.9
