### ISSUE TITLE
beinc.py - does not work at all

### ISSUE THREAD

**Issue by bvn13** [weechat/scripts#322]
Did you ever test it? It does not work at all!

1. Change this:
```
weechat.register(
    'beinc_weechat',
```
into 
```
weechat.register(
    'beinc',
```
**Reason**: weechat could not find script named neither 'beinc_weechat' nor 'beinc_weechat.py' nor 'beinc' because it was registered by one name but file hase another one.

2. Please provide us a simple `beinc_weechat.json` - it is neccessary and could not be empty because of you did not expect defaults.

https://i.imgur.com/N8ZQ9yl.png

**Comment by weechatter** [comment]
/script install beinc.py will install script.
Please read https://github.com/blackm0re/BEINC how to use and install all components to use the script
