### ISSUE TITLE
[ctrl_w.pl] Ctrl-W doesn't delete spaces at the beginning of a line

### ISSUE THREAD

**Issue by mgedmin** [weechat/scripts#375]
#### steps to reproduce

- install and enable ctrl_w.pl
- type a few spaces
- press ctrl-w

#### expectation

- the spaces get deleted

#### actual result

- nothing happens

**Comment by weechatter** [comment]
try to contact author please

**Comment by mgedmin** [comment]
Email sent!  (Wow that is one weird email address.)

**Comment by Juerd** [comment]
Thanks for the email, this issue can be closed now.

**Comment by mgedmin** [comment]
Ah, maybe I'll leave it open until the fixed version gets merged into this repo.
