### ISSUE TITLE
Irssi-notify

### ISSUE THREAD

**Issue by Merlincool** [weechat/scripts#439]
## Script
https://weechat.org/scripts/source/irssinotifier.py.html/
- Name of script: 
Irrsi-notify
## Question
1) There is no option to highlight any custom words, user wants. And can ignore rest of other stuffs.
2) I cant keep ON every notification linked to my name, I don't want that every time someone pings my name I get a notification.
3) The ignored buffers is not described how to use, i mean how to add custom words?, I tried to add word to it but it did not ignored the lines. And I still got notification.
4) I don't want every private chat to get notified, infact I want to filter lines in private chat. (Require some highlight functions)
5) `"only_away": "Only send notifications when set as away.",` how do you write that? What's the input? Yes or enabled or Ok?

Documentation on how to use values is incomplete. Please help us through each line and how to make an Input, I just can blacklist some nicks but rest is not usable.

This script is missing lot of customisation.

**Comment by weechatter** [comment]
the script looks for signals. It get a signal for highlight messages and private messages and does some action.

If you don't want every private chat to get notified, for example, change your weechat settings. see docs, 
how to change "notify level" and how to customise highlights:

https://weechat.org/files/doc/stable/weechat_user.en.html#notify_levels

**Comment by Merlincool** [comment]
I need that when I open my weechat buffer should get all the nick subjected buffers but I don't want my irssi notifier to notify every thing I get pinged, I just want to customise some words match. That will be notified in irssi-notifier, if I change the highlights and disable my nick notification from weechat, no doubt it will get disable from sending that notification but it will also get lost from the playback buffer. I hope I am not complicating what I need. Is there a way to highlight words in irrsi-notifier,I like to know the complete syntax and that will help me slove my issues.

**Comment by Merlincool** [comment]
> the script looks for signals. It get a signal for highlight messages and private messages and does some action.
> 
> If you don't want every private chat to get notified, for example, change your weechat settings. see docs,
> how to change "notify level" and how to customise highlights:
> 
> https://weechat.org/files/doc/stable/weechat_user.en.html#notify_levels
> 
> About "only_away" set value to "on" using /fset

The option is not using /fset, it's /set. The https://weechat.org/scripts/source/irssinotifier.py.html mentions how to use that.
