### ISSUE TITLE
issues with country.py

### ISSUE THREAD

**Issue by sorcerer420** [weechat/scripts#442]
## Script / WeeChat

- Name of script: country.py
- Script version: 0.6.1
- WeeChat version: 3.0

This bug has been reported to the script author? No
Response or reason: 

## Bug summary

errors when installing and using /country update

## Steps to reproduce

1. install script and attempt to /country update 
2. 
3. 

## Current behavior

[country] | Downloading IP database...
=!= | [country]   File "<string>", line 24
     print(e, file=sys.stderr)
                  ^
 SyntaxError: invalid syntax

**Comment by KaiserBarbarossa** [comment]
Could be closed now as country.py is removed

**Comment by flashcode** [comment]
Thanks for the info, closing this issue.
