### ISSUE TITLE
jabber.py: Which python/pip it's using?

### ISSUE THREAD

**Issue by SharkIng** [weechat/scripts#447]
## Script

- Name of script: jabber.py

## Question
I am trying to install this script, 'jabber.py' and it relay on the `XMPP` python library.
I am using MacOS terminal and it comes with few different python (versions). 

System default:
- `python`: Python 2.7.16
- `python3`: Python 3.8.2
- No `pip` installed

Homebrew:
- `python3`: Python 3.7.7 with `pip 19.3.1`
- `python`: Currently linked to `python3` with `pip3 20.0.2`

Virtualenv for WeeChat only:
- `python`: Using `python3` version 3.7.7 with `pip 20.3.3`

I know how to switch them, or activate any of them, use pip etc. However, when Jabber script require a library and it's been installed through any of the above mentioned `pip`, it doesn't work.

I checked the python version by using `/python version` inside WeeChat when it's running, it tells me that WeeChat is using 3.9.1 version. I am wondering which python instance weechat interact with? Is there a way to run WeeChat with virtualenv activated?

**Comment by weechatter** [comment]
Its recommended to use bitlbee instead of jabber.py.  jabber.py wasn't updated for at least 8 years.

Anyhow, I did "pip3 install xmpppy" with python 3.7.3 and pip3 18.1 and it worked as expected.

**Comment by SharkIng** [comment]
Thanks, 

After investigate it deeper, I think it's related how macos and homebrew handle different python version.
some notes for the future in case anyone else run into same issue:
- currently macos python is 2.* and locked. It seems like the `python` command will only use the system python, not `brew` one.
- try run `brew unlink python python3 && brew link python@_version_` to set correct python version to 3.8 or 3.9 which may help.

I'll close this issue.
