### ISSUE TITLE
meta: which GPL3 version applies

### ISSUE THREAD

**Issue by oxzi** [weechat/scripts#451]
## Script

All scripts which are tagged as "GPL3".

## Question

Lots of scripts specify their license as "GPL3", which is not a very specific identifier. The fourteenth paragraph of the [GNU GPL v3.0](https://www.gnu.org/licenses/gpl-3.0.en.html) states that later revisions do also apply if the "or any later version" section exists within the license note. To separate these two options, SPDX lists two distinct GPL 3 variants: [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) and [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html). The more general [GPL-3.0](https://spdx.org/licenses/GPL-3.0.html) SPDX identifier was deprecated.

If I am not wrong, I would say that WeeChat itself is licensed as "GPL-3.0-or-later", as specified in this [copyright file](https://github.com/weechat/weechat/blob/v3.0.1/debian-stable/copyright) or in this [file's header](https://github.com/weechat/weechat/blob/v3.0.1/src/core/weechat.h).

For packaging WeeChat scripts for third party package managers I would like to ask if this variant also applies to scripts. Additionally, I would love to see a more explicit license identifier being used.

Thanks for your time and all the hard work both for WeeChat and its ecosystem!

**Comment by weechatter** [comment]
i can change them for my scripts, if its really needed. but lot of authors are not active anymore.

**Comment by de-vri-es** [comment]
> For packaging WeeChat scripts for third party package managers I would like to ask if this variant also applies to scripts. Additionally, I would love to see a more explicit license identifier being used.

For each script, you should be able to find this information by looking at the script itself. They should also start with a license statement. You can't just assume the same conditions for all scripts. If the script doesn't make it clear, then you can't really be more specific.

My feeling is that the distinction is not important enough to make new releases for all GPL scripts. But I'll try to keep this in mind if I do an update anyway.

**Comment by oxzi** [comment]
@de-vri-es: I was primarily looking at the identifier alone, not additional copyright comments. Thanks for pointing that out.

However, while at least all started scripts contain additional text, this is not necessarily the case for other scripts. Thus I would find it nevertheless good, if it would be clarified, which GPL3 is generally meant.

**Comment by flashcode** [comment]
@oxzi: as mentioned here, each script has its own license and **must** mention it in the header (in order to be accepted in the official repository).
The identifier in database is just "GPL3", I'm not sure it's worth mentioning here that it's "GPL3 only" or "GPL3 or later".

So I close this issue, feel free to open specific issues if info is missing inside some scripts.
