### ISSUE TITLE
triggereply.py: TypeError

### ISSUE THREAD

**Issue by bialad** [weechat/scripts#459]
## Script / WeeChat

- Name of script: triggereply.py
- Script version: 0.4.2
- WeeChat version: 3.1

## Bug summary

Type error when running /triggerreply list:

TypeError: can only concatenate str (not "bytes") to str

And also when evaluating messages:

TypeError: translate() takes exactly one argument (2 given)

## Steps to reproduce

```
VERSION=3.1-1
apt-get install -y --no-install-recommends \
	weechat="$VERSION" \
	weechat-headless="$VERSION" \
	weechat-curses="$VERSION" \
	weechat-plugins="$VERSION" \
	weechat-python="$VERSION" \
	weechat-perl="$VERSION" \
```

1. Running weechat 3.1 in debian buster
2. /script install triggerreply.py 
3. /triggerreply list

**Comment by DeviantUK** [comment]
I can confirm.
Weechat 2.8, Ubuntu 20.04, Python 3.

**Comment by DeviantUK** [comment]
0.4.2 works with Python 2, but not with Python 3.

**Comment by weechatter** [comment]
then its not 100% python3 compatible. contact author, maybe he will still give support

**Comment by warshell** [comment]
Someone have information about author? @[fisherhu](https://github.com/fisherhu) @[flashcode](https://github.com/flashcode) @[vlad-s](https://github.com/vlad-s) ? Thanks! 

**Weechat 3.5**

- on add command Db insert error
- and on list it echos the code. 

Very goold plugin, i dont know others.
