### ISSUE TITLE
styurl.py: 00032. code at the beginning

### ISSUE THREAD

**Issue by diegoulloao** [weechat/scripts#469]
## Script / WeeChat

- Name of script: styurl
- Script version: 1.0
- WeeChat version: 3.1

Additional Information:
- OS: macOS Big Sur
- iTerm2
- Oh-my-zsh

This bug has been reported to the script author? Yes/No
Response or reason:  No

## Bug summary
Every time a new link is sent, a `00032` code appears at the beginning of the url string.

## Steps to reproduce

1. Wait for someone who send a link
2. Watch the link
3. See the bug

## Current behavior
`00032` code appears at the beginning of the url string so I can't click to open it. This happen only for new incoming links, the old ones are right.

![Captura de Pantalla 2021-06-10 a la(s) 11 01 38](https://user-images.githubusercontent.com/45423661/121549019-7d2c2d00-c9db-11eb-910b-950b3f7d37ac.png)

## Expected behavior
See the new urls without the code at the beginning in order to click on it.

## Suggested solutions
Check why this code is being concatenated at the beginning.

## Additional information
Only happen with new links that are sent, not the old ones.

**Comment by weechatter** [comment]
I can not reproduce, script works as expected.
By default, color 32 will be used for url. Seems like the color number will be add to the line.

You should check script options, especially: /fset plugins.var.python.styurl.format

**Comment by diegoulloao** [comment]
This helps?

![Captura de Pantalla](https://user-images.githubusercontent.com/45423661/121697064-b11a5780-ca9a-11eb-83a3-b5344801d8a7.png)

**Comment by flashcode** [comment]
Maybe a conflict with another script?
Can you try with only this script loaded?

**Comment by weechatter** [comment]
I had exactly the same (default) value. As flashcode suggested, try with only the script or give us the list of installed scripts
/script list

**Comment by diegoulloao** [comment]
@weechatter this is my list:
```bash
16:44 Scripts loaded:
16:44    ia   emoji.lua 5 (Emoji output helper)
16:44    ia   colorize_lines.pl 4.0 (Colorize users' text in chat area with their nick color, including highlights)
16:44  * ia   multiline.pl 0.6.3 (Multi-line edit box)
16:44  * ia   colorize_nicks.py 28 (Use the weechat nick colors in the chat area)
16:44  * ia   go.py 2.7 (Quick jump to buffers)
16:44    ia   himan.py 0.1 (What have they been saying about you?)
16:44    ia   notification_center.py 1.5.1 (Pass highlights and private messages to the macOS Notification Center)
16:44         slack.py 2.8.0 (Extends weechat for typing notification/search/etc on slack.com)
16:44    ia   styurl.py 1.0 (Style URLs with a Python regex)
16:44    ia   title.py 0.9 (Set screen title to current buffer name + hotlist items with configurable priority level)
16:44    ia   unread_buffer.py 2 (mark buffer as unread)
```

Any way to unload all except styurl ?

**Comment by weechatter** [comment]
yes, manually /script unload <scriptname>

**Comment by diegoulloao** [comment]
Sometimes this is happening too
https://user-images.githubusercontent.com/45423661/121790564-b7015d00-cbae-11eb-9763-41d43a5d9c94.mov

Link works good but after a fraction of time it loose the style

**Comment by weechatter** [comment]
i do not use slack. maybe you should ask weechat-slack. for me it seems its a problem when additional informations will be print.

**Comment by weechatter** [comment]
problem solved diegoulloao?

**Comment by diegoulloao** [comment]
Yes for this repository, I think the problem is on wee-slack 👍🏻 
Thank you.
