### ISSUE TITLE
urlserver.py's http_allowed_ips has a misleading example in the description

### ISSUE THREAD

**Issue by Fusl** [weechat/scripts#50]
Hi,

The description for plugins.var.python.urlserver.http_allowed_ips says

`regex for IPs allowed to use server (example: "^(123.45.67.89|192.160.*)$")`

which is wrong. A period (.) matches any single character but that's not much of an issue. What's an issue here is that the second IP with a wildcard in it is also notated wrong. People think (after reading the example) that IPs have to be pritten with a normal period and \* for a wildcard, but since this is regex, people using for example `123.45.6.*` will obviously match `123.45.6.*` but also `123.45.61._`, `123.45.63._`, `123.45.63.*`, ...

I suggest changing the description to hint the use of backslash escaping for regular expressions:

`^(123\.45\.67\.89|192\.160\..*)$`

**Comment by flashcode** [comment]
Hmm… the example is still wrong, I'll fix that.
