### ISSUE TITLE
Error in urlbar: weechat.look.color_nicks_number is obsolete

### ISSUE THREAD

**Issue by wimstefan** [weechat/scripts#51]
urlbar.py is giving this error recently:

<code>
python: error in function "urlbar_print_cb"
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/swimmer/.weechat/python/autoload/urlbar.py", line 177, in urlbar_print_cb
python: stdout/stderr:     urlobject = URL(url, get_buffer_name(buffer), time, prefix)
python: stdout/stderr:   File "/home/swimmer/.weechat/python/autoload/urlbar.py", line 143, in __init__
python: stdout/stderr:     self.nick = irc_nick_find_color(nick.strip('%&@+'))
python: stdout/stderr:   File "/home/swimmer/.weechat/python/autoload/urlbar.py", line 232, in irc_nick_find_color
python: stdout/stderr:     color %= weechat.config_integer(weechat.config_get("weechat.look.color_nicks_number"))
python: stdout/stderr: TypeError: not all arguments converted during string formatting
</code>

As stated in the #weechat channel that's due to an obsolete config variable.

**Comment by flashcode** [comment]
Pull request #92 has been merged.
