### ISSUE TITLE
colorize_lines.pl: Multi-line messages do not display

### ISSUE THREAD

**Issue by superjamie** [weechat/scripts#534]
## Script / WeeChat

- Name of script: `colorize_lines.pl`
- Script version: 4.0
- WeeChat version: 4.0.0

This bug has been reported to the script author? No

Response or reason: I thought this was the correct place to report script bugs? I will email the author too.

## Bug summary

Multi-line messages do not displayed properly. I can reproduce this with [wee-slack](https://github.com/wee-slack/wee-slack) by sending myself a multi-line message. The notification plugin displays the message properly. Removing `colorize_lines.pl` and restarting WeeChat displays the message properly.

This used to work fine on WeeChat 3.x, it's only broken with the change to WeeChat 4.0.

## Steps to reproduce

1. Install WeeChat 4.0.0
2. Install wee-slack - https://github.com/wee-slack/wee-slack
3. Connect to a Slack team, you can connect to your own team for $0
4. Send a multi-line message to yourself with `line1<Alt+enter>line2`

## Current behavior

Only the first line of the message `line1` is displayed

## Expected behavior

Both lines of the message `line1` then `line2` are displayed

## Additional information

* WeeChat version: 4.0.0
* OS, distribution and version:  Ubuntu 22.04
* Terminal: Terminator 2.1.1
* Terminal multiplexer (screen/tmux/…/none): none

**Comment by flashcode** [comment]
For your information, this is not specific to wee-slack, I can reproduce on an IRC channel with multiline enabled, steps to reproduce:

1. Install script colorize_lines.pl
2. Add ergo server: `/server add ergo testnet.ergo.chat`
3. `/connect ergo` (capability `draft/multiline` should be automatically enabled)
4. `/join #testchan`
5. Send a message with 2 lines

Actual result: only first line is displayed.
