### ISSUE TITLE
buffers.pl automatic scrolling

### ISSUE THREAD

**Issue by NoSuck** [weechat/scripts#56]
It would be nice if the buffer bar automatically scrolled to include the active buffer.  Here is a demonstration of what I mean.  The buffer bar is at the top.

Current behavior:

![Current, non-scrolling buffers.pl](https://nosuckdotorg.files.wordpress.com/2015/02/2015e5b9b402e69c8810e697a5e3808103e6998248e5888627e7a792-weechat-buffers-lack-of-autoscroll.gif)

Desired behavior:

![This would be an awesome feature](https://nosuckdotorg.files.wordpress.com/2015/02/2015e5b9b402e69c8810e697a5e3808103e6998249e5888649e7a792-weechat-buffers-autoscroll.gif)

A similar feature request seems to have been brought up [some years ago](http://savannah.nongnu.org/task/?11280).

**Comment by flashcode** [comment]
This feature should be preferably added in weechat itself, not the script (or not only the script).
Please open same feature request in weechat repository.
I keep this one opened, because depending on implementation, it will maybe require some changes in script as well.

**Comment by flashcode** [comment]
The script buffers.pl is now deprecated, replaced by built-in plugin buflist (added in WeeChat 1.8), which has an auto-scroll option, see: `/help buflist.look.auto_scroll` (option added in WeeChat 1.9).
So I close this issue.

**Comment by NoSuck** [comment]
Thank you!  I checked it out.  Sadly, this option has no effect for `position = top` or `bottom` bars.

**Comment by flashcode** [comment]
Yes, this works only with position left/right and a vertical filling.
