### ISSUE TITLE
[colorize_nicks.py] Version 16 breaks colorization in weetweet (and probably other similar scripts)

### ISSUE THREAD

**Issue by DarkDefender** [weechat/scripts#58]
db27274ecc73c55c10cda5c96e74b3cd3db23e8a breaks nick colorization in my weetweet plugin.

Before all nicks added to the buffer nick list got correctly colorized. Now no nicks gets any color what so ever...

@holomorph can you help me solve this issue? I'm not sure what exactly broke between version 15 and 16 that would cause this.

**Comment by holomorph** [comment]
If you can find a different script that breaks on it (as I don't use twitter), I'd be more inclined to help.

**Comment by DarkDefender** [comment]
@holomorph I've created a "test" version of my script that doesn't need a twitter account or the python twitter lib.
https://github.com/DarkDefender/weetweet/tree/color-debug

Just load it in weechat and it should print out some sample tweets. With version 15 of colorize nicks, every nick gets properly colored. However with 16 none of them are colored.

This is with weechat 1.1.1 and python2 as weechat python version.

**Comment by holomorph** [comment]
Thanks for that; I'm able to reproduce

**Comment by holomorph** [comment]
You can see in my branch the change is split into two commits. https://github.com/holomorph/scripts/commits/colorize_nicks.py

Looks like just "use weechat config facilities" breaks coloring in weetweet

**Comment by DarkDefender** [comment]
Thanks @holomorph. I found the problem.

I the code before the update to the new config scheme, "ignore_channels = w.config_string(colorize_config_option['blacklist_channels']).split(',')"
(line 304 in version 16) was guarded by a if statement. If I comment out this line colorization works again.

I don't know why this is the case. But I guess that ignore_channels needs to have valid string in it or stuff like this happens.

**Comment by holomorph** [comment]
I don't think that if statement made sense: if someone clears the option, will the blacklist get updated?

Following from that, I think this is the real problem
```python
if channel in ignore_channels:
        return line
```
because `twitter` isn't a channel, channel is an empty string, and because if there is nothing configured in the blacklist, its value is `['']`, that will return because `"" in ['']` is True.  So a possible fix is:
```python
if channel and channel in ignore_channels:
    return line
```

**Comment by holomorph** [comment]
Hmph, the regex doesn't play nice with greedy matching off

**Comment by DarkDefender** [comment]
Ok, thank you so much! :) Should I leave this issue open till your pull request is in?

**Comment by holomorph** [comment]
Yeah that makes sense
