### ISSUE TITLE
query_blocker: add option for working only on specific networks (comma-separated)?

### ISSUE THREAD

**Issue by Mikaela** [weechat/scripts#79]
I am using umode +g _(my blog: [1](https://mikaela.info/english/2015/04/02/umode+g.html) & [2](https://mikaela.info/english/2015/05/10/umode+g2.html))_ on all networks that support it, but sadly not all networks have it. For those it would be nice to be able to tell query_blocker to only block queries on those networks even if it's lesser and client-side form of the same thing.

Networks that I am on and don't have it:
- dereferenced
  - not implemented yet
- ircnet
  - won't ever happen
- mozilla
  - I don't understand why they don't have it (because module isn't loaded, but why?) as it's supported by InspIRCd.

IRCnet brings me most of unwanted queries and I get a lot of stress/anxiety from not having any kind of protection against it. Because I use ZNC this issue wouldn't help so much either, but it would be at least a little help.

**Comment by weechatter** [comment]
i added a new function to easily ignore a server. simply add a localvar for corresponding server:
/buffer set localvar_set_query_blocker 1

https://github.com/weechatter/weechat-scripts/blob/master/perl/query_blocker.pl
