### ISSUE TITLE
A new Color feature for iset

### ISSUE THREAD

**Issue by highflyer77** [weechat/scripts#93]
A new Feature that would really, really be sweet is when viewing iset options, is that anything with a color name or number value in it would show that color in iset. 

Would make it much easier to see the color option you wish to change and
especially when using alt-- , alt-shft-+ , to change the color.

You could then view the color change on the fly, without having to revert to the /color command to find a color number to make the change.

awesome :)

**Comment by highflyer77** [comment]
Would this not be pretty easy to impliment?

It seems like it should be

**Comment by weechatter** [comment]
https://github.com/weechatter/weechat-scripts/blob/master/perl/iset.pl
